let imagesGames = [
  "images/assassins-creed-brotherhood.jpg",
  "images/assassins-creed-syndicate.jpg",
  "images/batman-arkham-asylum.jpg",
  "images/batman-arkham-city.jpg",
  "images/batman-arkham-origins.jpg",
  "images/batman-arkham-knight.jpg",
  "images/darksiders-ii.jpg",
  "images/grand-theft-auto-iv.jpg",
  "images/grand-theft-auto-v.jpg",
  "images/grand-theft-auto-san-andreas.jpg",
  "images/hitman-2016.jpg",
  "images/hitman-2.jpg",
  "images/hitman-3.jpg",
  "images/lords-of-the-fallen.jpg",
  "images/mad-max.jpg",
  "images/mafia.jpg",
  "images/middle-earth-shadow-of-mordor.jpg",
  "images/murdered-soul-suspect.jpg",
  "images/prince-of-persia.jpg",
  "images/prince-of-persia-warrior-within.jpg",
  "images/quantum-break.jpg",
  "images/sleeping-dogs-definitive-edition.jpg",
  "images/the-witcher-3-wild-hunt.jpg",
  "images/battleborn.jpg",
  "images/battlefield-3.jpg",
  "images/battlefield-4.jpg",
  "images/battlefield-hardline.jpg",
  "images/battlefield-bad-company-2.jpg",
  "images/bioshock-infinite.jpg",
  "images/borderlands.jpg",
  "images/borderlands-the-pre-sequel.jpg",
  "images/call-of-duty-advanced-warfare.jpg",
  "images/call-of-duty-black-ops.jpg",
  "images/call-of-duty-modern-warfare-3.jpg",
  "images/crysis.jpg",
  "images/crysis-3.jpg",
  "images/dead-island.jpg",
  "images/dead-space-3.jpg",
  "images/defiance.jpg",
  "images/destiny-2.jpg",
  "images/doom.jpg",
  "images/doom-3-bfg-edition.jpg",
  "images/escape-dead-island.jpg",
  "images/evolve.jpg",
  "images/far-cry.jpg",
  "images/far-cry-2.jpg",
  "images/far-cry-4.jpg",
  "images/fear.jpg",
  "images/fear-2-project-origin.jpg",
  "images/homefront.jpg",
  "images/homefront-the-revolution.jpg",
  "images/medal-of-honor.jpg",
  "images/medal-of-honor-warfighter.jpg",
  "images/metro-2033.jpg",
  "images/overwatch.jpg",
  "images/prey.jpg",
  "images/red-faction-guerrilla.jpg",
  "images/sniper-ghost-warrior-3.jpg",
  "images/star-trek.jpg",
  "images/star-wars-battlefront.jpg",
  "images/star-wars-the-force-unleashed-ii.jpg",
  "images/the-bureau-xcom-declassified.jpg",
  "images/the-darkness-ii.jpg",
  "images/the-division.jpg",
  "images/the-evil-within.jpg",
  "images/titanfall.jpg",
  "images/titanfall-2.jpg",
  "images/ghost-recon-advanced-warfighter-2.jpg",
  "images/rainbow-six-siege.jpg",
  "images/splinter-cell-double-agent.jpg",
  "images/wolfenstein-the-new-order.jpg",
  "images/wolfenstein-ii-the-new-colossus.jpg",
  "images/diablo-iii.jpg",
  "images/mass-effect-2.jpg",
  "images/mass-effect-3.jpg",
  "images/mass-effect-andromeda.jpg",
  "images/the-technomancer.jpg",
  "images/world-of-warcraft.jpg",
  "images/act-of-aggression.jpg",
  "images/anno-2070.jpg",
  "images/civilization-v.jpg",
  "images/command-conquer-red-alert-3.jpg",
  "images/starcraft-ii-wings-of-liberty.jpg",
  "images/starcraft-ii-heart-of-the-swarm.jpg",
  "images/starcraft-ii-legacy-of-the-void.jpg",
  "images/state-of-decay.jpg",
  "images/blood-bowl.jpg",
  "images/blur.jpg",
  "images/f1-2010.jpg",
  "images/f1-2011.jpg",
  "images/f1-2014.jpg",
  "images/f1-2016.jpg",
  "images/f1-2017.jpg",
  "images/f1-2018.jpg",
  "images/flatout-ultimate-carnage.jpg",
  "images/forza-horizon.jpg",
  "images/nascar-14.jpg",
  "images/need-for-speed-rivals.jpg",
  "images/ultra-street-fighter-iv.jpg",
  "images/de-sims-4.jpg",
  "images/the-sims-super-deluxe.jpg",
  "images/south-park-the-fractured-but-whole.jpg",
];

let ListOfGames = [
  "Assassin's Creed: Brotherhood",
  "Assassin's Creed: Syndicate",
  "Batman: Arkham Asylum",
  "Batman: Arkham City",
  "Batman: Arkham Origins",
  "Batman: Arkham Knight",
  "Darksiders II",
  "Grand Theft Auto IV",
  "Grand Theft Auto V",
  "Grand Theft Auto: San Andreas",
  "Hitman (2016)",
  "Hitman 2",
  "Hitman 3",
  "Lords of the Fallen",
  "Mad Max",
  "Mafia",
  "Middle-earth: Shadow of Mordor",
  "Murdered: Soul Suspect",
  "Prince of Persia",
  "Prince of Persia: Warrior Within",
  "Quantum Break",
  "Sleeping Dogs (Definitive Edition)",
  "The Witcher 3: Wild Hunt",
  "Battleborn",
  "Battlefield 3",
  "Battlefield 4",
  "Battlefield Hardline",
  "Battlefield: Bad Company 2",
  "BioShock Infinite",
  "Borderlands",
  "Borderlands: The Pre-Sequel!",
  "Call of Duty: Advanced Warfare",
  "Call of Duty: Black Ops",
  "Call of Duty: Modern Warfare 3",
  "Crysis",
  "Crysis 3",
  "Dead Island",
  "Dead Space 3",
  "Defiance",
  "Destiny 2",
  "Doom",
  "Doom 3: BFG Edition",
  "Escape Dead Island",
  "Evolve",
  "Far Cry",
  "Far Cry 2",
  "Far Cry 4",
  "F.E.A.R.",
  "F.E.A.R. 2: Project Origin",
  "Homefront",
  "Homefront: The Revolution",
  "Medal of Honor",
  "Medal of Honor: Warfighter",
  "Metro 2033",
  "Overwatch",
  "Prey",
  "Red Faction: Guerrilla",
  "Sniper: Ghost Warrior 3",
  "Star Trek",
  "Star Wars: Battlefront",
  "Star Wars: The Force Unleashed II",
  "The Bureau: XCOM Declassified",
  "The Darkness II",
  "The Division",
  "The Evil Within",
  "Titanfall",
  "Titanfall 2",
  "Ghost Recon: Advanced Warfighter 2",
  "Rainbow Six: Siege",
  "Splinter Cell: Double Agent",
  "Wolfenstein: The New Order",
  "Wolfenstein II: The New Colossus",
  "Diablo III",
  "Mass Effect 2",
  "Mass Effect 3",
  "Mass Effect: Andromeda",
  "The Technomancer",
  "World of Warcraft",
  "Act of Aggression",
  "Anno 2070",
  "Civilization V",
  "Command & Conquer: Red Alert 3",
  "StarCraft II: Wings of Liberty",
  "StarCraft II: Heart of the Swarm",
  "StarCraft II: Legacy of the Void",
  "State of Decay",
  "Blood Bowl",
  "Blur",
  "F1 2010",
  "F1 2011",
  "F1 2014",
  "F1 2016",
  "F1 2017",
  "F1 2018",
  "FlatOut: Ultimate Carnage",
  "Forza Horizon",
  "NASCAR '14",
  "Need for Speed: Rivals",
  "Ultra Street Fighter IV",
  "De Sims 4",
  "The Sims: Super Deluxe",
  "South Park: The Fractured But Whole"
];

const gamesList = {

}