const initialGames = [
  "Assassin's Creed: Brotherhood",
  "Assassin's Creed II + Brotherhood",
  "Assassin's Creed: Syndicate",
  "Batman: Arkham Asylum",
  "Batman: Arkham City",
  "Batman: Arkham Origins",
  "Batman: Arkham Knight",
  "Darksiders II",
  "Grand Theft Auto IV",
  "Grand Theft Auto V",
  "Grand Theft Auto: San Andreas",
  "Hitman (The Complete First Season)",
  "Lords of the Fallen",
  "Mad Max",
  "Mafia",
  "Middle-earth: Shadow of Mordor",
  "Murdered: Soul Suspect",
  "Prince of Persia",
  "Prince of Persia: Warrior Within",
  "Quantum Break",
  "Sleeping Dogs (Definitive Edition)",
  "The Witcher 3: Wild Hunt",
  "Battleborn",
  "Battlefield 3",
  "Battlefield 4",
  "Battlefield Hardline",
  "Battlefield: Bad Company 2",
  "Battlefield: Bad Company 2 - Vietnam",
  "BioShock Infinite",
  "Borderlands",
  "Borderlands: The Pre-Sequel!",
  "Borderlands Add-on Pack",
  "Call of Duty: Advanced Warfare",
  "Call of Duty: Black Ops",
  "Call of Duty: Modern Warfare 3",
  "Crysis",
  "Crysis 3",
  "Dead Island",
  "Dead Space 3",
  "Defiance",
  "Destiny 2",
  "Doom",
  "Doom 3: BFG Edition",
  "Escape Dead Island",
  "Evolve",
  "Far Cry",
  "Far Cry 2",
  "Far Cry 4",
  "F.E.A.R.",
  "F.E.A.R. 2: Project Origin",
  "Homefront",
  "Homefront: The Revolution",
  "Medal of Honor",
  "Medal of Honor: Warfighter",
  "Metro 2033",
  "Overwatch",
  "Prey",
  "Red Faction: Guerrilla",
  "Sniper: Ghost Warrior 3",
  "Star Trek",
  "Star Wars: Battlefront",
  "Star Wars: The Force Unleashed II",
  "The Bureau: XCOM Declassified",
  "The Darkness II",
  "The Division",
  "The Evil Within",
  "Titanfall",
  "Titanfall 2",
  "Ghost Recon: Advanced Warfighter 2",
  "Rainbow Six: Siege",
  "Splinter Cell: Double Agent",
  "Wolfenstein: The New Order",
  "Wolfenstein II: The New Colossus",
  "Diablo III",
  "Diablo III: Reaper of Souls",
  "Mass Effect 2",
  "Mass Effect 3",
  "Mass Effect: Andromeda",
  "The Technomancer",
  "World of Warcraft",
  "Act of Aggression",
  "Anno 2070",
  "Civilization V",
  "Command & Conquer: Red Alert 3",
  "Maelstrom",
  "StarCraft + Expansion Set",
  "StarCraft II: Wings of Liberty",
  "StarCraft II: Heart of the Swarm",
  "StarCraft II: Legacy of the Void",
  "State of Decay",
  "Blood Bowl",
  "Blur",
  "F1 2010",
  "F1 2011",
  "F1 2014",
  "F1 2016",
  "F1 2017",
  "F1 2018",
  "FlatOut: Ultimate Carnage",
  "Forza Horizon",
  "NASCAR '14",
  "Need for Speed: Rivals",
  "Ultra Street Fighter IV",
  "De Sims 4",
  "De Sims 4: Ecologisch Leven",
  "The Sims: Super Deluxe",
  "South Park: The Fractured But Whole"
];
